name: Build FlashInfer Wheel

# This allows you to manually trigger the build from the Actions tab
on:
  workflow_dispatch:

jobs:
  build_wheel:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Get the source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Set up CUDA 12.8 (This is the most important step)
      - name: Set up CUDA
        uses: nv-actions/setup-cuda@v1
        with:
          cuda-version: '12.8'

      # 4. Install build dependencies, including PyTorch for CUDA 12.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          # Install PyTorch that matches the CUDA version
          pip install torch --index-url https://download.pytorch.org/whl/cu128
          # Install other build tools
          pip install ninja cmake

      # 5. Build the wheel file
      - name: Build Wheel
        run: |
          # This command builds the wheel and places it in the 'dist' folder
          pip wheel . -w dist

      # 6. Upload the built wheel as an artifact
      - name: Upload Wheel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flashinfer-wheel-py310-cu128
          path: dist/
